# Generated by Django 3.2.7 on 2021-09-19 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('product_id', models.IntegerField(max_length=50)),
                ('article', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('product_type', models.CharField(max_length=50)),
                ('bar_code', models.CharField(max_length=50)),
                ('sup_price', models.FloatField(max_length=50)),
                ('cust_price', models.FloatField(max_length=50)),
                ('disc_per', models.FloatField(max_length=50)),
                ('disc_amount', models.FloatField(max_length=50)),
                ('ex_date', models.DateField(max_length=50)),
                ('qty', models.IntegerField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.color')),
                ('hsn_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.hsncode')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.style')),
            ],
        ),
    ]
