# Generated by Django 3.2.7 on 2021-09-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
