# Generated by Django 3.2.7 on 2021-09-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210919_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='article',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
